baseURL = 'https://yearone.io/'
languageCode = 'en-us'
title = 'YEARONE'
theme = "hugo-creative-portfolio-theme"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
# Style options: default (pink), blue, green, pink, red, sea, violet
# Use custom.css for your custom styling
style = "default"
description = "web3 dev shop"
copyright = "&copy;2024 Yearone IO"
sidebarAbout = [
    "Dev shop.",
    "⚡️ Rapid MVPers and prototypers.",
    "🫡 Experienced in early stage product development.",
    "🕵️‍♂️ Deep knowledge in web3, ethereum and Lukso LSPs.",
    "🏅 Winners of LUKSO #BuildUp2 hackathon and LUKSO Grants Program.",
    "✉️ If you want to bring your ideas to life, reach out to us!",
]
# Contact page
# Since this template is static, the contact form uses www.formspree.io as a
# proxy. The form makes a POST request to their servers to send the actual
# email. Visitors can send up to a 1000 emails each month for free.
#
# What you need to do for the setup?
#
# - set your email address under 'email' below
# - upload the generated site to your server
# - send a dummy email yourself to confirm your account
# - click the confirm link in the email from www.formspree.io
# - you're done. Happy mailing!
email = "hello@yearone.io"

# Optional Matomo analytics (formerly piwik)
# [params.analytics.matomo]
#  URL = "https://stats.example.com"
#  ID = "42"
#  # Track all subdomains with "*.example.com" (Optional)
#  domain = "www.example.com"
#  # Optional integrity check hash
#  hash = ""

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = "portfolio/"
home = true

[params.social]
#facebook      = "full page or profile url in facebook"
#googleplus    = "full profile url in googleplus"
email         = "hello@yearone.io"
twitter       = "https://x.com/YearOneIO/"
#linkedin      = "full profile url in linkedin"
#stackoverflow = "full profile url in stackoverflow"
#instagram     = "full profile url in instagram"
github        = "https://github.com/yearone-io/"
#gitlab        = "full profile url in gitlab"
#youtube       = "full profile url in youtube"
#whatsapp      = "wa.me service link"